spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/room9?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100

logging:
  level:
    org:
      hibernate:
        SQL: debug
        type: trace

#AWS
cloud:
  aws:
    s3:
      bucket: room9
    region:
      static: ap-northeast-2
    stack:
      auto: false

#S3 Folder
room9:
  room: room

#JWT
#jwt:
#  secret: cm9vbTlyMDBtOWdvb21vb25nZ29vbW9vbmdnMDBtMDBuZ2cwMG1vb25nZ29vbTAwbmcK
#  access-token-expired-time: 2592000000